// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL5VHkp3Meptn7dIgoGWeaDXII699t9gU',
    appId: '1:356863653231:android:1fb7d977a1d780a3a1649a',
    messagingSenderId: '356863653231',
    projectId: 'flutter101-covid-fo',
    storageBucket: 'flutter101-covid-fo.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaj3Azl52kZEuXMlySw7t2l9ES9ndAaQ',
    appId: '1:356863653231:web:561edd9cc9f2e1efa1649a',
    messagingSenderId: '356863653231',
    projectId: 'flutter101-covid-fo',
    authDomain: 'flutter101-covid-fo.firebaseapp.com',
    storageBucket: 'flutter101-covid-fo.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsR-fh4qEryzvLcZSfNYxGzBLTGGl4jvY',
    appId: '1:356863653231:ios:fa35e0d8fbe988e3a1649a',
    messagingSenderId: '356863653231',
    projectId: 'flutter101-covid-fo',
    storageBucket: 'flutter101-covid-fo.firebasestorage.app',
    iosBundleId: 'com.example.covidForm',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsR-fh4qEryzvLcZSfNYxGzBLTGGl4jvY',
    appId: '1:356863653231:ios:fa35e0d8fbe988e3a1649a',
    messagingSenderId: '356863653231',
    projectId: 'flutter101-covid-fo',
    storageBucket: 'flutter101-covid-fo.firebasestorage.app',
    iosBundleId: 'com.example.covidForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzaj3Azl52kZEuXMlySw7t2l9ES9ndAaQ',
    appId: '1:356863653231:web:d5e54379193f5af0a1649a',
    messagingSenderId: '356863653231',
    projectId: 'flutter101-covid-fo',
    authDomain: 'flutter101-covid-fo.firebaseapp.com',
    storageBucket: 'flutter101-covid-fo.firebasestorage.app',
  );

}